### ISSUE TITLE
fetch categories to filter items with them

### ISSUE THREAD

**Issue by rmsrob** [cefop/BobbleMixNextJs#1]
Right now the categories filter is hardcoded.
We need to fetch category then dispatch all items if one or more is present inside items.
ex: the item "classic iceberg" got "classic" and "menthe" as categories. this item should be present inside both categories.
if a category doesn't own any product then don't show this category.

**Comment by Mickey101987** [comment]
Create the function allowing to map the categories having items and to display the items by category. If the item name contains a category name, this item is displayed in that category.
